apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinglist
  labels:
    app: bookinglist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinglist
  template:
    metadata:
      labels:
        app: bookinglist
    spec:
      containers:
        - name: bookinglist
          image: 052937454741.dkr.ecr.ap-northeast-2.amazonaws.com/team-e-bookinglist:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5